Improve stashing changes

diff --git a/git-tug b/git-tug
--- a/git-tug
+++ b/git-tug
@@ -31,11 +31,9 @@ pull_branch() {
 
     echo "Pulling $BRANCH"
 
-    git stash -u || exit 1
     git checkout $BRANCH || exit 1
     git pull --rebase || exit 1
     git checkout $CURRENT_BRANCH || exit 1
-    git stash pop || exit 1
 }
 
 check_branch() {
@@ -90,13 +88,29 @@ main() {
         esac
     done
 
+    git stash list | grep -- '--- git-tug ---' > /dev/null
+    if [ $? -eq 0 ]
+    then
+        echo "A previous git-tug execution exited with an error."
+        echo "Resolve any problems first and remove the '--- git-tug ---' stash entry."
+        exit 1
+    fi
+
     # Fetch remote
-    echo "Fetching from remote repository" && git fetch || exit 1
+    echo "Fetching from remote repository" && git fetch || exit 2
+
+    echo "Stashing local changes" && git stash save -u -- "--- git-tug ---" || exit 2
 
     for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/)
     do
         check_branch $branch
     done
+
+    git stash list | grep -- '--- git-tug ---' > /dev/null
+    if [ $? -eq 0 ]
+    then
+        echo "Reaplying local changes" && git stash pop || exit 2
+    fi
 }
 
 main $@
